services:
  - type: web
    name: flaskedit
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
      - key: TEMP_FOLDER
        value: /tmp/temp_conversions 